### ISSUE TITLE
Crash moment

### ISSUE THREAD

**Issue by DreamSt4n** [douira/sodium-fabric#11]
### Bug Description

java.lang.NoClassDefFoundError: com/lodborg/intervaltree/Interval
	at me.jellysquid.mods.sodium.client.render.chunk.gfni.GFNI.addSectionInNewNormalLists(GFNI.java:160) ~[sodium-fabric-mc1.20.1-0.5.2+git.3e652b1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.gfni.GFNI.integrateTranslucentData(GFNI.java:217) ~[sodium-fabric-mc1.20.1-0.5.2+git.3e652b1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processChunkBuildResults(RenderSectionManager.java:328) ~[sodium-fabric-mc1.20.1-0.5.2+git.3e652b1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:306) ~[sodium-fabric-mc1.20.1-0.5.2+git.3e652b1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:190) ~[sodium-fabric-mc1.20.1-0.5.2+git.3e652b1.jar:?]
	at net.minecraft.class_761.method_3273(class_761.java:6033) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1247) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.ClassNotFoundException: com.lodborg.intervaltree.Interval
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 15 more

### Reproduction Steps

nuh uh

### Attach Log File

nuh uh

### Attach Crash Report

nuh uh

**Comment by DreamSt4n** [comment]
Fixed.
