### ISSUE TITLE
Crash on chunk load when Transluency Sorting is enabled

### ISSUE THREAD

**Issue by StunfMC** [douira/sodium-fabric#14]
### Bug Description

Upon loading into some worlds, your game will crash on load of certain chunks.

### Reproduction Steps

Create a world and watch as the game crashes on load of certain chunks.

### Log File

[00:29:26] [Chunk Render Task Executor #7/ERROR]: Chunk build failed
java.nio.BufferOverflowException: null
	at java.nio.Buffer.nextPutIndex(Buffer.java:722) ~[?:?]
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:359) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.data.TranslucentData.writeQuadVertexIndexes(TranslucentData.java:80) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.data.AnyOrderData.fromMesh(AnyOrderData.java:50) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.TranslucentGeometryCollector.makeNewTranslucentData(TranslucentGeometryCollector.java:459) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.TranslucentGeometryCollector.getTranslucentData(TranslucentGeometryCollector.java:550) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:171) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:46) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:45) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:187) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:29:26] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: Exception thrown while executing job
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:383) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:293) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:212) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at net.minecraft.class_761.method_3273(class_761.java:7767) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1020) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:866) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:722) ~[?:?]
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:359) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.data.TranslucentData.writeQuadVertexIndexes(TranslucentData.java:80) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.data.AnyOrderData.fromMesh(AnyOrderData.java:50) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.TranslucentGeometryCollector.makeNewTranslucentData(TranslucentGeometryCollector.java:459) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.TranslucentGeometryCollector.getTranslucentData(TranslucentGeometryCollector.java:550) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:171) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:46) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:45) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:187) ~[sodium-fabric-mc1.20.3-0.5.5+git.ef490ba.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:29:26] [Server thread/INFO]: Stopping server
[00:29:26] [Server thread/INFO]: Saving players
[00:29:26] [Server thread/INFO]: Saving worlds
[00:29:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[00:29:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[00:29:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[00:29:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[00:29:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[00:29:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[00:29:33] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[00:29:33] [Render thread/INFO]: Stopping worker threads

### Crash Report

---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-12-30 00:29:34
Description: Unexpected error

java.lang.RuntimeException: Exception thrown while executing job
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:383)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:293)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:212)
	at net.minecraft.class_761.method_3273(class_761.java:7767)
	at net.minecraft.class_761.method_22710(class_761.java:1020)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.BufferOverflowException
	at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:722)
	at java.base/java.nio.DirectIntBufferU.put(DirectIntBufferU.java:359)
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.data.TranslucentData.writeQuadVertexIndexes(TranslucentData.java:80)
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.data.AnyOrderData.fromMesh(AnyOrderData.java:50)
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.TranslucentGeometryCollector.makeNewTranslucentData(TranslucentGeometryCollector.java:459)
	at me.jellysquid.mods.sodium.client.render.chunk.translucent_sorting.TranslucentGeometryCollector.getTranslucentData(TranslucentGeometryCollector.java:550)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:171)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:46)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:45)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:187)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:383)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:293)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:212)
	at net.minecraft.class_761.method_3273(class_761.java:7767)
	at net.minecraft.class_761.method_22710(class_761.java:1020)
	at net.minecraft.class_757.method_3188(class_757.java:1098)

-- Uptime --
Details:
	JVM uptime: 83.781s
	Wall uptime: 77.481s
	High-res time: 75.882s
	Client ticks: 1274 ticks / 63.700s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['DreamWasBad'/130, l='ClientLevel', x=155.32, y=76.00, z=27.44]]
	Chunk stats: 4096, 663
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,91,32), Section: (at 0,11,0 in 10,5,2; chunk contains blocks 160,-64,32 to 175,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 57 game time, 1 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 114

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Fabrication, Fabrication Grayscale, seamless:default_seamless, file/Vanilla Reimagined

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 774231592 bytes (738 MiB) / 1577058304 bytes (1504 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Graphics card #1 name: Intel(R) UHD Graphics 770
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x4680
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3616
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34607.87
	Virtual memory used (MB): 12853.57
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amplified_nether: Amplified Nether 1.2.4
		architectury: Architectury 11.0.9
		audaki_cart_engine: Audaki Cart Engine 2.0.6
		bettermounthud: Better Mount HUD 1.2.2
		blasting_plus_mr: Blasting Plus 1.1
		blastingraw: BlastingRaw 1.20.3-1-fabric
		boatbreakfix: Boat Break Fix 1.0.11
		bundle_recipe: Bundle Recipe 1-v1.0.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.38
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.38
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.38
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.38
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.38
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.38
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.38
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.38
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.38
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.38
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.38
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.38
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.38
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.38
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.38
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.38
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.38
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.38
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.38
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.38
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.38
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		carpet: Carpet Mod 1.4.128+v231205
		chatpatches: Chat Patches 204.6.1
		clean-debug: Clean F3 0.4.3
		cloth-config: Cloth Config v13 13.0.114
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.4+1.20.2
		cursorcenteredfix: CursorCentered Fix 1.0
		dark-loading-screen: Dark Loading Screen 1.6.14
		debugify: Debugify 1.20.4+1.0
		disableaccessibilityscreen: DisableAccessibilityScreen 1.0.1
		disablechristmaschests: Disable Christmas Chests 1.2.0
		dynamic_fps: Dynamic FPS 3.3.2
		entityculling: EntityCulling 1.6.3.1
		fabric-api: Fabric API 0.92.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.0+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.8+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabrication: Fabrication 3.4.5+1.20.4
			lib39-deferral: Lib39 (Deferral) 1.5.0-pre2.2+1.19.3
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		ferritecore: FerriteCore 6.0.3
		fixbookgui: Fix Book Gui Mod 1.5.0+1.20.4
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.2.0
		forceselectworld: Force Select World 1.0.0
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		head_in_the_clouds: Head In The Clouds 1.0.1
		hopobettermineshaft: Hopo Better Mineshaft 1.1.9
		hopobetterruinedportal: Hopo Better Ruined Portal 1.3.7
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.1.4
		immediatelyfast: ImmediatelyFast 1.2.8+1.20.4
			net_lenni0451_reflect: Reflect 1.3.1
		indium: Indium 1.0.28+mc1.20.4
		java: OpenJDK 64-Bit Server VM 17
		joinautosprint: JoinAutoSprintMod 1.0.1
		krypton: Krypton 0.2.4
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		libreexpfix: LibreExpFix 0.2.2b9-BETA
		lithium: Lithium 0.12.1
		lithostitched: Lithostitched 1.0.0
		mes: Moog's End Structures 1.3-1.20-fabric
		midnightlib: MidnightLib 1.5.3
		minecraft: Minecraft 1.20.4
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.10.2+mc1.20.4
		moreculling: More Culling 1.20.1-0.19.0
			conditional-mixin: conditional mixin 0.3.2
		mr_dungeons_andtaverns: Dungeons and Taverns 3.1.1
		mr_dungeons_andtavernspillageroutpostrework: Dungeons and Taverns Pillager Outpost Rework 1.3
		mr_dungeons_andtavernsstrongholdrework: Dungeons and Taverns Stronghold Rework 1.1.1
		mr_dungeons_andtavernsswamphutrework: Dungeons and Taverns Swamp Hut Rework 1.1
		mr_mastercutter: MasterCutter 1.1
		mr_regrown: Regrown 1.1.2
		mr_reimagined_trims: Reimagined Trims 1.0.3
		mru: Mineblock's Repeated Utilities 0.4.0+1.20.4
		name_visibility: Better Name Visibility 1.1
		nochatreports: No Chat Reports 1.20.4-v2.5.0
		nogizmo: No Debug Gizmo 1.8
		noisium: Noisium 1.0.2+mc1.20.x
		noreportbutton: No Report Button 1.5.0
		notenoughanimations: NotEnoughAnimations 1.6.4
		nullscape: Nullscape 1.2.4
		optionfocusfix: Option Focus Fix 1.3.0
		raised: Raised 3.1.0
		reeses-sodium-options: Reese's Sodium Options 1.7.0+mc1.20.2-build.97
		removerodblocking: RemoveRodBlocking 1.0.1+1.19.3-1.20.x
		revitalized_outposts: Revitalized Outposts 1.0.0
		seamless: Seamless 2.2.1
		shieldfixes: Walksy's Shield Fixes 1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		skinlayers: 3d Skin Layers 1.5.6-mc1.20.2
		skinpr: SkinPartsRefresher 1.0.3
		snowundertrees: Snow Under Trees 2.1.0+1.20.4
		sodium: Sodium 0.5.5+git.ef490ba
			com_lodborg_interval-tree: interval-tree 1.0.0
		sspb: Sodium Shadowy Path Blocks 3.2.1
		timeless: Timeless 1.20.2-1.2.0
		visuality: Visuality 0.7.3+1.20.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.1+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.15.3-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.99, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 14/14 chunks
	Resource Packs: vanilla, fabric, Fabrication (incompatible), Fabrication grayscale, seamless:default_seamless, file/Vanilla Reimagined
	Current Language: en_us
	Locale: en_US
	CPU: 24x 12th Gen Intel(R) Core(TM) i9-12900K
	Server Running: true
	Player Count: 1 / 8; [class_3222['DreamWasBad'/130, l='ServerLevel[New World]', x=155.32, y=76.00, z=27.44]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental

**Comment by DreamSt4n** [comment]
This was a mistake on my end, this issue was because of something else. Closing report.
